model_list:
  - model_name: qwen-80b
    litellm_params:
      model: openai/nvidia:qwen/qwen3-next-80b-a3b-instruct
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
      extra_headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

  - model_name: qwen-122b
    litellm_params:
      model: openai/nvidia:qwen/qwen3.5-122b-a10b
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
      extra_headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

  - model_name: kimi-k2-new
    litellm_params:
      model: openai/nvidia:moonshotai/kimi-k2-instruct-0905
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
      extra_headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

  - model_name: kimi-k2-old
    litellm_params:
      model: openai/nvidia:moonshotai/kimi-k2-instruct
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
      extra_headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

  - model_name: cerebras
    litellm_params:
      model: openai/cerebras:qwen-3-235b-a22b-instruct-2507
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
      extra_headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

  - model_name: longcat
    litellm_params:
      model: openai/longcat:LongCat-Flash-Chat
      api_base: os.environ/NVIDIA_API_BASE
      api_key: os.environ/NVIDIA_API_KEY
      extra_headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

router_settings:
  routing_strategy: "simple-shuffle"
  fallbacks:
    - qwen-80b: ["qwen-122b", "kimi-k2-new", "kimi-k2-old", "cerebras", "longcat"]
  num_retries: 1
  enable_pre_call_checks: true

litellm_settings:
  allowed_fails: 2
  cooldown_time: 30
  callbacks: ["handler.custom_handler"]
